In [1]:
import sqlite3
import pandas as pd

In [2]:
# accès à la table departement pour afficher son contenu
connexion = sqlite3.connect('Database.db')
cursor = connexion.cursor()

query =  '''SELECT 
        offres.intitule,
        offres.poste,
        offres.profil,
        offres.description_offre,
        offres.date_creation,
        offres.salaire_min_annuel,
        offres.salaire_max_annuel,
        offres.salaire_annuel_mean,
        offres.qualification_libelle,
        offres.experience,
        offres.type_contrat,
        offres.secteur_activite,
        offres.id_ville,
        offres.id_entreprise,
        d_ville.id,
        d_ville.ville,
        d_ville.latitude,
        d_ville.longitude,
        d_ville.code_postal,
        d_ville.departement,
        d_entreprise.id,
        d_entreprise.entreprise_nom,
        d_entreprise.entreprise_description,
        h_departement.departement,
        h_departement.departement_nom,
        h_departement.region
        
        FROM offres
        INNER JOIN d_ville ON offres.id_ville = d_ville.id
        INNER JOIN d_entreprise ON offres.id_entreprise = d_entreprise.id
        INNER JOIN h_departement ON d_ville.departement = h_departement.departement;
        '''

df = pd.read_sql_query(query, connexion)

connexion.close()

In [3]:
df

,intitule,poste,profil,description_offre,date_creation,salaire_min_annuel,salaire_max_annuel,salaire_annuel_mean,qualification_libelle,experience,...,latitude,longitude,code_postal,departement,id,entreprise_nom,entreprise_description,departement,departement_nom,region
0,Senior Data Engineer F/H (H/F),data engineer,None,"Le saviez-vous ?\r\n\r\nNous rejoindre, c'est ...",29/12/2023,None,None,None,None,oui,...,49.687882,1.395968,76270.0,seine-maritime,2,None,"Nous rejoindre, c'est rejoindre l'un des leade...",seine-maritime,seine-maritime,normandie
1,Data Engineer H/F,data engineer,None,"Rejoindre le Groupe IRCEM, c'est participer à ...",29/12/2023,None,None,None,None,oui,...,50.688369,3.181903,59100.0,nord,3,IRCEM,None,nord,nord,hauts-de-france
2,Analytics Engineer F/H - Marketing (H/F),data engineer,None,Descriptif du poste:\r\n\r\nRôle : L Analytics...,29/12/2023,None,None,None,Cadre,oui,...,48.742795,2.394977,94310.0,val-de-marne,4,CPF,"Depuis 2002, Amorino émerveille les gourmands ...",val-de-marne,val-de-marne,île-de-france
3,DATA ENGINEER - H/F,data engineer,None,Description :\r\n\r\n\r\nvous rejoindrez une é...,28/12/2023,45000.0,55000.0,50000.0,None,oui,...,47.873504,1.917316,45100.0,loiret,6,DSI Pôle Emploi,None,loiret,loiret,centre-val de loire
4,DATA ENGINEER - H/F,data engineer,None,Description :\r\n\r\n\r\nvous rejoindrez une é...,28/12/2023,45000.0,55000.0,50000.0,None,oui,...,43.536112,5.398630,13080.0,bouches-du-rhône,6,DSI Pôle Emploi,None,bouches-du-rhône,bouches-du-rhône,provence-alpes-côte d'azur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,PhD / Jeune Docteur - Data scientist & IA F/H,data scientist,CE QUE NOUS RECHERCHONS\r\nVous êtes titulaire...,LE PROJET Nous recherchons un(e) Chef(fe) de p...,19/12/2023,None,None,None,Cadre du secteur privé,non,...,43.596038,1.432095,31100.0,haute-garonne,226,CAPGEMINI,"CAPGEMINI Capgemini, qu'est-ce que cela évoque...",haute-garonne,haute-garonne,occitanie
267,Analyste développeur - data scientist F/H,data scientist,"Diplômé d’un Bac+5 scientifique, vous possédez...",L’arrivée à maturité de solutions informatique...,06/12/2023,None,None,None,Cadre du secteur privé,non,...,48.571265,7.767760,67000.0,bas-rhin,228,EURO-INFORMATION DEVELOPPEMENTS,"Euro-Information, filiale technologique de Cré...",bas-rhin,bas-rhin,grand est
268,Data scientist / Chargé(e) d'études sur la pet...,data scientist,Etes-vous notre prochain(e) Data scientist ?\r...,Concrètement votre futur quotidien ?\r\nVous p...,28/12/2023,None,None,None,Cadre du secteur privé,oui,...,48.829262,2.326537,75014.0,paris,229,CNAF,Vous souhaitez rejoindre une équipe expériment...,paris,paris,île-de-france
269,Expert en sciences des données spécialisé en I...,data scientist,Expérience :\r\nAu moins 5 ans d'expérience en...,Mission :\r\nEn tant que Data scientist spécia...,18/12/2023,None,None,None,Cadre du secteur public / Armées,oui,...,48.840072,2.292837,75015.0,paris,230,DIRECTION DU NUMÉRIQUE DES MINISTÈRES SOCIAUX,Vous souhaitez intégrer une Direction numériqu...,paris,paris,île-de-france
270,Data scientist / Chargé(e) d'études sur la pet...,data scientist,\r\nTitulaire d'un bac+5 en statistiques et/o...,\r\nConcrètement votre futur quotidien ?\r\nV...,19/12/2023,None,None,None,Cadre du secteur privé,non,...,48.829262,2.326537,75014.0,paris,231,CNAF,Vous souhaitez rejoindre une équipe expériment...,paris,paris,île-de-france

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   poste                   271 non-null    object
 1   intitule                271 non-null    object
 2   description_offre       271 non-null    object
 3   profil                  106 non-null    object
 4   date_creation           271 non-null    object
 5   salaire_min_annuel      63 non-null     object
 6   salaire_max_annuel      57 non-null     object
 7   salaire_annuel_mean     63 non-null     object
 8   qualification_libelle   182 non-null    object
 9   experience              271 non-null    object
 10  type_contrat            271 non-null    object
 11  secteur_activite        214 non-null    object
 12  ville                   271 non-null    object
 13  latitude                271 non-null    float64
 14  longitude               271 non-null    float64
 15  code_postal             271 non-null    object
 16  ville_departement       271 non-null    object
 17  entreprise_nom          225 non-null    object
 18  entreprise_description  199 non-null    object
 19  departement             271 non-null    object
 20  departement_nom         0 non-null      object
 21  region                  271 non-null    object
dtypes: float64(2), object(20)
memory usage: 46.7+ KB